// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ywncrmllteghysizvdcm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl3bmNybWxsdGVnaHlzaXp2ZGNtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc4NDM3MTEsImV4cCI6MjA1MzQxOTcxMX0.KKk2jijMLVt3mdmSOfOIZo21Tk_YtHP-9gnanTsPg1g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);